From centos
MAINTAINER rooping <2539263027@qq.com>

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN yum -y update
# tool
RUN yum install -y openssh-server
RUN yum install -y openssh-clients
RUN yum install -y net-tools
RUN yum install -y git vim
RUN yum install -y tree traceroute
RUN yum install -y cscope ctags
# c language
RUN yum install -y gdb
# golang
RUN yum install -y golang
# python
RUN yum install -y epel-release
RUN yum install -y python3-pip
RUN yum install -y python3

